;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
	'(
		 ac-pcmp/self-insert-command-with-ac-start
		 c-electric-brace
		 count-words-region
		 create-balise
		 indent-for-tab-command
		 kill-region
		 kmacro-insert-counter
		 kmacro-start-macro-or-insert-counter
		 org-end-of-line
		 org-self-insert-command
		 suspend-frame
		 tab-to-tab-stop
		 ))

(setq mc/cmds-to-run-once
	'(
		 ace-jump-done
		 ace-jump-mode
		 ace-jump-move
		 ace-jump-quick-exchange
		 ace-mc-add-char
		 ace-mc-add-multiple-cursors
		 ace-mc-add-single-cursor
		 ace-mc-do-keyboard-reset
		 helm-show-kill-ring
		 next-buffer
		 overwrite-mode
		 pop-global-mark
		 previous-buffer
		 ))
